### ISSUE TITLE
How to use cde with freechipsproject/chisel-template

### ISSUE THREAD

**Issue by ilongshan** [chipsalliance/cde#30]
How to setup to use this project with freechipsproject/chisel-template?

**Comment by sequencer** [comment]
unrelated issue to this project, you can use this project from ivy via `org.chipsalliance::cde`, or directly use it from source, you can take a look at https://github.com/chipsalliance/rocket-chip/blob/026f4c9f18a5e077f4f9903771eec31da9f4bccf/build.sc#L9
